package-lock.json
package.json
src/background/appInit.ts
src/background/controllers/browserUtils.ts
src/background/services/approval.ts
src/background/services/identity.ts
src/background/services/lock.ts
src/background/shared/initGlobals.ts
src/custom.d.ts
src/ui/components/ConfirmRequestModal/index.tsx
src/ui/components/CreateIdentityModal/CreateIdentityModal.tsx
src/ui/components/CreateIdentityModal/__tests__/CreateIdentityModal.test.tsx
src/ui/components/FullModal/index.tsx
src/ui/components/Icon/index.tsx
src/ui/components/Menuable/index.tsx
src/ui/components/Modal/index.tsx
src/ui/ducks/identities.ts
src/ui/pages/Home/components/IdentityList/IdentityItem.tsx
src/ui/pages/Home/components/IdentityList/IdentityList.tsx
src/ui/pages/Home/components/IdentityList/__tests__/IdentityItem.test.tsx
src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx
src/ui/pages/Home/components/IdentityList/index.ts
src/ui/pages/Home/components/index.ts
src/ui/pages/Home/index.tsx
tsconfig.json

There is a bug with `IdentityService` because it use two separate stores to keep identities.
In this PR I removed inheritance from `SimpleStorage` for `IdentityStorage` and use composition instead.
In addition, I added some tests for `IdentityList` component and refactored it.
Fixes #133
N/A
1. Try to add new identity
2. Remove this identity
3. Reload page or lock extension
4. You will see identity list without this identity

fix: delete identity

---

src/background/services/__tests__/approvalService.test.ts
src/background/services/approval.ts
src/background/zkKeeper.ts
src/contentScripts/injected.ts

This PR has a breaking change for approval store so need to reinstall the extension.
Blocked by #135 
N/A
1. Reinstall the extension
2. Try to use permanent approves or just approve every operation

refactor: approval service

---

.eslintrc.js
.github/CODEOWNERS
.github/dependabot.yml
.github/workflows/check.yml
.husky/commit-msg
.husky/pre-commit
.husky/pre-push
commitlint.config.js
package-lock.json
package.json
src/background/services/protocols/__tests__/utils.test.ts
src/background/services/protocols/utils.ts

This PR adds some ci checks and enables pre-push and commit message checks for local development.
In addition, I added dependabot file to create PR for dependency updates automatically.
Closes #74
Closes #94
Closes #95
N/A
N/A

chore: ci checks and git hooks

---

src/background/services/__tests__/approvalService.test.ts
src/background/services/__tests__/identityService.test.ts
src/background/services/__tests__/lockService.test.ts
src/background/services/approval.ts
src/background/services/identity.ts
src/background/services/lock.ts
src/background/zkKeeper.ts
src/ui/hooks/wallet/__tests__/useWallet.test.ts

This PR contains refactoring and tests for `LockService`.
Blocked by #138 
N/A
Everything should work as before (encryption, decryption, lock, unlock).

refactor: lock service

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml

Added bug report template.
Closes #38 
N/A
N/A

chore: add bug report template

---

.github/dependabot.yml
demo/index.html
demo/index.tsx
demo/package-lock.json
demo/package.json
package-lock.json

Updated demo dependencies to get rid of security issues in github and trigger dependabot for demo dependencies.
Related to #40 
N/A
Demo should work as worked before

chore: update demo dependencies and add dependabot trigger

---

.eslintrc.new.js
src/contentScripts/index.ts
src/contentScripts/injected.ts
src/contentScripts/proof/__tests__/rln.test.ts
src/contentScripts/proof/__tests__/semaphore.test.ts
src/contentScripts/proof/rln.ts
src/contentScripts/proof/semaphore.ts
src/types/index.ts

This is a third PR for new linter config. There are some fixes for content scripts.
Related to #142 
Blocked by #170 
N/A
N/A

chore: eslint fixes for content scripts

---

README.md
demo/index.tsx
src/background/controllers/browserUtils.ts
src/background/controllers/requestManager.ts
src/background/services/__tests__/identityService.test.ts
src/background/services/identity.ts
src/background/zkKeeper.ts
src/types/index.ts
src/ui/ducks/identities.ts

chore:
- Making sure to clean any pendingRequested related to any opened window which is closed from the user via clicking on "x" button.
enhance:
- Adding a button for creating a new identity in the demo website.
Fixes #187 
Closes #14
Related to #140  
Related to #183 

fix: clean pending requests

---

.eslintrc.js
package-lock.json
package.json
src/background/backgroundPage.ts
src/background/services/__tests__/lockService.test.ts
src/background/services/lock.ts
src/background/zkKeeper.ts
src/contentScripts/index.ts
src/setupTests.ts
src/ui/components/Input/index.tsx
src/ui/components/Menuable/Menuable.tsx
src/ui/components/Menuable/useMenuable.ts
src/ui/ducks/__tests__/app.test.tsx
src/ui/ducks/app.ts
src/ui/pages/Home/components/IdentityList/Item/index.tsx
src/ui/pages/Login/Login.tsx
src/ui/pages/Login/__tests__/Login.test.tsx
src/ui/pages/Login/__tests__/useLogin.test.ts
src/ui/pages/Login/useLogin.ts
src/ui/pages/Popup/Popup.tsx
src/ui/pages/Popup/__tests__/Popup.test.tsx
src/ui/pages/Popup/__tests__/usePopup.test.ts
src/ui/pages/Popup/usePopup.ts

This PR adds support for new form management tool to improve validation and state management in the future.
For now, it's done as-is for Login page.
Related to #191 
N/A
1. Try to login with correct/wrong/empty password
2. You can see error messages for wrong or empty password and will be redirecting to approve step if password is correct

feat: add react-hook-form library

---

package-lock.json
package.json

Upgrading `rlnjs` package from the npm registry.  

chore: upgrade rlnjs pacakge from npm registry

---

src/background/services/approval.ts
src/background/zkKeeper.ts

Making approvals storage persistent. 
- Fixes #250 
N/A
N/A
1. Open any Dapp to connect (demo, or zkitter)
2. Connect with CK and make sure to check `This site is requesting access to view your current identity. Always make sure you trust the site you interact  with.`
3. Then refresh the extension from the refresh button in the extensions page ![Image](https://user-images.githubusercontent.com/36774944/230949195-143f7411-d393-49a5-86f8-898aebd95a16.png)
4. Try to reconnect again to the dapp you connected to in step (2)
5. You won't see the approval screen appearing again since you already approved. 

fix: bug #250 not persistent approvals

---

src/ui/pages/Home/components/ActivityList/ActivityList.tsx
src/ui/pages/Home/components/ActivityList/activityListStyles.scss
src/ui/pages/Home/components/IdentityList/IdentityList.tsx
src/ui/pages/Home/components/IdentityList/identityListStyles.scss
src/ui/pages/Home/components/TabList/tabListStyles.scss

This PR stick footer to bottom on tab list for home page.
N/A
1. Go to Identities tab or to Activity tab
2. Check styles for both tabs

feat: sticky footer for home tab list

---

.eslintrc.js
e2e/pages/BasePage.ts
e2e/pages/cryptKeeper/Activity.ts
e2e/pages/cryptKeeper/CryptKeeper.ts
e2e/pages/cryptKeeper/Identities.ts
e2e/pages/cryptKeeper/Settings.ts
src/background/controllers/browserUtils.ts
src/background/controllers/handler.ts
src/background/controllers/requestManager.ts
src/background/identityDecorater.ts
src/background/services/approval.ts
src/background/services/history/index.ts
src/background/services/identity.ts
src/background/services/lock.ts
src/background/services/notification.ts
src/background/services/protocols/rln.ts
src/background/services/protocols/semaphore.ts
src/background/services/simpleStorage.ts
src/background/services/validation/artifact.ts
src/background/services/validation/merkle.ts
src/background/services/wallet.ts
src/background/zkKeeper.ts
src/connectors/mock.ts
src/contentScripts/proof/rln.ts
src/contentScripts/proof/semaphore.ts

Adding no-public eslint rule
N/A
N/A
N/A

chore: adding no-public eslint rule

---

e2e/tests/proofGeneration.test.ts
playwright.config.ts
src/server/mockMerkleProof.ts

This PR adds e2e tests for proof generation.
Closes #237 
N/A
N/A

test: add e2e tests for proof generation

---

src/background/cryptKeeper.ts
src/background/services/approval/__tests__/approvalService.test.ts
src/background/services/approval/index.ts
src/background/services/backup/BackupService.ts
src/background/services/backup/__tests__/BackupService.test.ts
src/background/services/backup/index.ts
src/background/services/backup/types.ts
src/background/services/lock/__tests__/lockService.test.ts
src/background/services/lock/index.ts
src/background/services/zkIdentity/__test__/zkIdentity.test.ts
src/background/services/zkIdentity/index.ts
src/constants/rpcActions.ts
src/types/backup/index.ts
src/types/index.ts

This PR adds backup service and supports password check for uploading backups.
Related to #257 
Blocked by #279 
N/A
N/A

feat: backup service

---

.eslintrc.js
src/background/cryptKeeper.ts
src/background/services/approval/__tests__/approvalService.test.ts
src/background/services/approval/index.ts
src/background/services/crypto/index.ts
src/background/services/lock/__tests__/lockerService.test.ts
src/background/services/lock/index.ts
src/background/services/zkIdentity/__test__/zkIdentity.test.ts
src/background/services/zkIdentity/index.ts
src/connectors/utils.ts
src/contentScripts/injected.ts
src/ui/components/Menuable/useMenuable.ts

This PR adds additional tests for services.
N/A
N/A
N/A

test: add tests for services

---

.github/workflows/e2e.yml
e2e/pages/cryptKeeper/Settings.ts
e2e/tests/backup.test.ts

This PR adds e2e tests for backup downloading.
Closes #332 
N/A
N/A

test: add e2e tests for backup download

---

demo/index.tsx
demo/useCryptKeeper.ts
e2e/tests/proofGeneration.test.ts
src/background/contentScript.ts
src/background/services/event/types.ts
src/providers/sdk/Base.ts
src/setupTests.ts

This PR removes accounts from user sdk and disables demo RLN proof generation
N/A
N/A
N/A

fix: remove accounts

---

src/background/controllers/__tests__/requestManager.test.ts
src/background/controllers/requestManager.ts
src/background/cryptKeeper.ts
src/background/services/approval/__tests__/approvalService.test.ts
src/background/services/approval/index.ts
src/background/services/injector/__tests__/injector.test.ts
src/background/services/injector/index.ts
src/background/services/injector/types.ts
src/constants/rpcActions.ts
src/providers/sdk/Base.ts
src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/__tests__/useConnectionApprovalModal.test.ts
src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/useConnectionApprovalModal.ts
src/ui/components/ConnectionModal/__tests__/useConnectionModal.test.ts
src/ui/components/ConnectionModal/useConnectionModal.ts
src/ui/ducks/__tests__/permissions.test.tsx
src/ui/ducks/permissions.ts

This PR is a part of splitting #445.
N/A
N/A

refactor: background handler

---

packages/app/src/background/cryptKeeper.ts
packages/app/src/background/services/wallet/__tests__/walletService.test.ts
packages/app/src/background/services/wallet/index.ts
packages/app/src/types/wallet/index.ts
packages/app/src/ui/ducks/__tests__/app.test.tsx
packages/app/src/ui/ducks/app.ts
packages/app/src/ui/pages/Login/Login.tsx
packages/app/src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts
packages/app/src/ui/pages/Recover/__tests__/Recover.test.tsx
packages/app/src/ui/pages/Recover/__tests__/useRecover.test.ts
packages/app/src/ui/pages/Recover/useRecover.ts
packages/providers/src/constants/rpcAction.ts

This PR adds check mnemonic rpc method for recovery screen.
Related to #572 
Blocked by #574 
N/A
N/A

feat: add check mnemonic rpc

---

packages/app/src/types/index.ts
packages/app/src/types/verifiableCredentials/index.ts

chore: enhance jsdocs with types

---

packages/app/manifest.chrome.json
packages/app/package.json
packages/app/src/background/backgroundPage.ts
packages/app/src/background/shared/__tests__/utils.test.ts
packages/app/src/background/shared/utils.ts
packages/app/src/constants/index.ts
packages/app/src/offscreen/__tests__/offscreenHtml.test.ts
packages/app/src/offscreen/index.html
packages/app/src/offscreen/index.ts
packages/types/src/request/index.ts
pnpm-lock.yaml

This PR adds support of Offscreen page only for CHROME browsers.
* Closes #623 
N/A
N/A

feat: supporting offscreen feature for chrome platform

---

packages/app/src/background/services/approval/__tests__/approvalService.test.ts
packages/app/src/background/services/approval/index.ts
packages/app/src/background/services/backup/BackupService.ts
packages/app/src/background/services/backup/__tests__/BackupService.test.ts
packages/app/src/background/services/lock/index.ts
packages/app/src/background/services/wallet/index.ts
packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
packages/app/src/background/services/zkIdentity/index.ts
packages/app/src/types/backup/index.ts

This PR adds support for backup merge.
Closes #328 
N/A
N/A

feat: merge backup with current data

---

.env.example
.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/e2e.yml
packages/app/src/background/services/approval/__tests__/approvalService.test.ts
packages/app/src/background/services/approval/index.ts
packages/app/src/background/services/backup/BackupService.ts
packages/app/src/background/services/backup/types.ts
packages/app/src/background/services/crypto/CryptoService.ts
packages/app/src/background/services/crypto/__tests__/crypto.test.ts
packages/app/src/background/services/lock/__tests__/lockerService.test.ts
packages/app/src/background/services/lock/index.ts
packages/app/src/background/services/wallet/__tests__/walletService.test.ts
packages/app/src/background/services/wallet/index.ts
packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
packages/app/src/background/services/zkIdentity/index.ts
packages/e2e/fixtures/index.ts
packages/e2e/pages/cryptKeeper/Settings.ts
packages/e2e/playwright.config.ts
packages/e2e/tests/backup.test.ts

This PR changes backup file structure and adds additional checks for backup data.
Blocked by #661
Related to #330 
N/A
N/A

feat: backup file format

---

.github/workflows/check.yml
.github/workflows/deploy.yml
.github/workflows/healthCheck.yml
package.json
packages/e2e/fixtures/index.ts
packages/e2e/package.json
packages/e2e/tests/backup.test.ts
packages/e2e/tests/identity.test.ts
packages/e2e/tests/initialization.test.ts
packages/e2e/tests/proofGeneration.test.ts
packages/e2e/tests/recover.test.ts

This PR optimizes checks for PR, main push.
Blocked by #668 
N/A
N/A

chore: optimize checks

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml

This PR adds artifacts signing for release assets.
Related to #675 - waits for release to check the workflow
N/A
N/A

chore: build gpg signing

---

.github/workflows/release.yml
package.json

Add fixes for release pipeline
N/A
N /A

chore: release support

---

package.json

chore: skip root changelog generation [skip ci]

---

.github/workflows/release.yml

Use PAT for release automation.
N/A
N/A

chore: use pat for release pipeline [skip ci]

---

.github/workflows/release.yml
package.json

chore: fix release pipeline [skip ci]

---

.prettierignore
package.json
packages/app/src/setupTests.ts
packages/providers/src/index.ts

fix: release pipeline

---

.github/workflows/release.yml
package.json
packages/app/project.json
packages/providers/project.json

chore: release fixes

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml
package.json
packages/providers/project.json
pnpm-lock.yaml

Fix publishing packages
N/A
N/A

fix: publish packages

---

.github/workflows/publishPackages.yml
packages/providers/project.json

Publish packages using pnpm
N/A
N//A

fix: publish with pnpm

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml

Use protected tags for release
N/A
N/A

fix: tags for release

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml

Fixes store publish pipeline
N/A
N/A

fix: store publish

---

.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml
.github/workflows/release.yml

fix: signing key import

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml
.github/workflows/release.yml

fix: gpg key import

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml
.github/workflows/release.yml

Fix GPG signing order and pass additional args
N/A
N/A

fix: gpg signing order and args

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml
.github/workflows/release.yml

fix: release workflow

---

.github/workflows/release.yml

Change release publisher
N/A
N/A

fix: change release publisher

---

.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml
package.json
packages/app/src/manifest/v2/manifest.firefox.json
packages/app/src/manifest/v3/manifest.chrome.json
packages/app/src/manifest/v3/manifest.firefox.json
packages/providers/package.json
packages/providers/src/index.ts

Fix firefox and providers publish
N/A
N/A

fix: firefox and providers publish

---

.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml
packages/app/src/manifest/v2/manifest.firefox.json
packages/app/src/manifest/v3/manifest.chrome.json
packages/app/src/manifest/v3/manifest.firefox.json
packages/providers/src/index.ts

Fix firefox store publish
N/A
N/A

fix: firefox store publish

---

README.md
packages/app/src/manifest/v2/manifest.firefox.json
packages/app/src/manifest/v3/manifest.chrome.json
packages/app/src/manifest/v3/manifest.firefox.json

docs: updating README with RLN protocol

---

.github/workflows/webExtLint.yml
packages/app/src/background/shared/subworkers.js

This PR prepares for firefox release
N/A
N/A

chore: release preparations for firefox

---

packages/app/project.json
packages/app/src/manifest/v2/manifest.firefox.json
packages/app/src/manifest/v3/manifest.firefox.json
packages/providers/src/index.ts

Fixes for firefox publish
N/A
N/A

fix: firefox publish

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml
packages/app/src/setupTests.ts
packages/providers/src/index.ts

fix: release versions

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
packages/app/project.json
packages/manifest-bump/project.json

Use latest manifest version for release store publish
N/A
N/A

chore: use latest manifest version for release

---

packages/e2e/pages/cryptKeeper/CryptKeeper.ts
packages/e2e/pages/cryptKeeper/Groups.ts
packages/e2e/tests/groups.test.ts

This PR adds e2e tests for group interaction.
Closes #316
Blocked by #873 
N/A
N/A

test: group e2e tests

---

.github/workflows/release.yml

This PR changes release publisher to @CryptkeeperZKBot.
Closes #828 
N/A
N/A

chore: change release publisher

---

.github/workflows/publishPackages.yml
packages/types/package.json
packages/zk/package.json

This PR adds types and zk packages for release pipeline
N/A
N/A
N/A

chore: add release workflow for types and zk packages

---

.github/workflows/release.yml

Return release publisher back
Related #828 
N/A
N/A

chore: return release publisher

---

packages/app/src/background/services/credentials/__tests__/credentials.test.ts
packages/app/src/background/services/credentials/index.ts
packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
packages/app/src/background/services/zkIdentity/index.ts
packages/app/src/config/mock/zk.ts
packages/app/src/types/verifiableCredentials/index.ts
packages/app/src/ui/components/DropdownButton/DropdownButton.tsx
packages/app/src/ui/components/DropdownButton/__tests__/DropdownButton.test.tsx
packages/app/src/ui/components/DropdownButton/__tests__/useDropdownButton.test.ts
packages/app/src/ui/components/DropdownButton/index.ts
packages/app/src/ui/components/DropdownButton/useDropdownButton.ts
packages/app/src/ui/hooks/verifiableCredentials/__tests__/useCryptkeeperVerifiableCredentials.test.tsx
packages/app/src/ui/pages/AddVerifiableCredential/__tests__/AddVerifiableCredential.test.tsx
packages/app/src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
packages/app/src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
packages/app/src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
packages/app/src/ui/pages/CreateIdentity/useCreateIdentity.ts
packages/app/src/ui/pages/Identity/Identity.tsx
packages/app/src/ui/pages/PresentVerifiableCredential/PresentVerifiableCredential.tsx
packages/app/src/ui/pages/PresentVerifiableCredential/__tests__/PresentVerifiableCredential.test.tsx
packages/app/src/ui/pages/PresentVerifiableCredential/__tests__/usePresentVerifiableCredential.test.ts
packages/app/src/ui/pages/PresentVerifiableCredential/usePresentVerifiableCredential.ts
packages/e2e/pages/cryptKeeper/Identities.ts
packages/types/src/identity/index.ts
packages/zk/src/identity/factory/__tests__/factory.test.ts
packages/zk/src/identity/factory/index.ts

This PR improves identity creation process and adds deterministic values to metadata.
Related to #889 
<details>
<summary>Expand</summary>
</details>
Try to create identity with different signature options and check the identity page

feat: update identity creation

---

packages/app/src/background/services/lock/index.ts
packages/app/src/constants/paths.ts
packages/app/src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx
packages/app/src/ui/pages/GroupMerkleProof/__tests__/useGroupMerkleProof.test.ts
packages/app/src/ui/pages/Identity/__tests__/useIdentityPage.test.ts
packages/app/src/ui/pages/ImportIdentity/ImportIdentity.tsx
packages/app/src/ui/pages/ImportIdentity/__tests__/ImportIdentity.test.tsx
packages/app/src/ui/pages/ImportIdentity/__tests__/useImportIdentity.test.ts
packages/app/src/ui/pages/ImportIdentity/index.ts
packages/app/src/ui/pages/ImportIdentity/useImportIdentity.ts
packages/app/src/ui/pages/JoinGroup/__tests__/useJoinGroup.test.ts
packages/app/src/ui/pages/Popup/Popup.tsx
packages/app/src/ui/pages/RevealIdentityCommitment/__tests__/useRevealIdentityCommitment.test.ts
packages/providers/src/services/event/types.ts
packages/providers/src/services/handler/index.ts

This PR adds import identity page.
Related to #906 
N/A
N/A

feat: add import identity page

---

packages/app/src/config/mock/zk.ts
packages/app/src/ui/components/BigNumberInput/BigNumberInput.tsx
packages/app/src/ui/components/BigNumberInput/__tests__/BigNumberInput.test.tsx
packages/app/src/ui/components/BigNumberInput/__tests__/useBigNumberInput.test.ts
packages/app/src/ui/components/BigNumberInput/index.ts
packages/app/src/ui/components/BigNumberInput/useBigNumberInput.ts
packages/app/src/ui/components/ConfirmRequestModal/components/RlnProofModal/RlnProofModal.tsx
packages/app/src/ui/components/ConfirmRequestModal/components/SemaphoreProofModal/SemaphoreProofModal.tsx
packages/app/src/ui/components/IdentityList/Item/index.tsx
packages/app/src/ui/components/Input/index.tsx
packages/app/src/ui/components/Input/input.scss
packages/app/src/ui/components/PasswordInput/PasswordInput.tsx
packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
packages/app/src/ui/pages/DownloadBackup/DownloadBackup.tsx
packages/app/src/ui/pages/ImportIdentity/ImportIdentity.tsx
packages/app/src/ui/pages/ImportIdentity/__tests__/ImportIdentity.test.tsx
packages/app/src/ui/pages/ImportIdentity/__tests__/useImportIdentity.test.ts
packages/app/src/ui/pages/ImportIdentity/useImportIdentity.ts
packages/app/src/ui/pages/Login/Login.tsx
packages/app/src/ui/pages/Onboarding/Onboarding.tsx
packages/app/src/ui/pages/OnboardingBackup/OnboardingBackup.tsx
packages/app/src/ui/pages/ResetPassword/ResetPassword.tsx
packages/app/src/ui/pages/RevealMnemonic/RevealMnemonic.tsx
packages/app/src/ui/pages/UploadBackup/UploadBackup.tsx
packages/zk/src/index.ts
packages/zk/src/proof/protocols/__tests__/utils.test.ts
packages/zk/src/proof/protocols/index.ts
packages/zk/src/proof/protocols/utils.ts

This PR changes input styles for the application.
Related to #906
<details>
<summary>Expand</summary>
</details>
N/A

feat: update input styles

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds reviewers checklist to the PR template
N/A
N/A
N/A

chore: add reviewers checklist to the PR template

---

.github/PULL_REQUEST_TEMPLATE.md
packages/app/src/background/services/approval/index.ts
packages/demo/useCryptKeeper.ts
packages/providers/src/services/event/types.ts

This PR adds new approval event to handle demo connection.
Related to #1011
N/A
1. Check approval add/revoke
2. Check login/logout

feat: add approval event

---

.github/workflows/publishChrome.yml
.github/workflows/publishFirefox.yml
.github/workflows/publishPackages.yml

This PR removes build and packages signs.
N/A
N/A
N/A

fix: remove build sign

---

packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
packages/demo/index.tsx
packages/e2e/pages/cryptKeeper/Identities.ts
packages/e2e/tests/importExternalIdentity.test.ts
packages/types/package.json
packages/zk/package.json

This PR adds e2e tests for import external identity feature
Related to #906 
N/A
N/A

test: import identity e2e

---

packages/app/jest.config.js
packages/app/src/background/cryptKeeper.ts
packages/app/src/background/services/credentials/__tests__/credentials.test.ts
packages/app/src/background/services/credentials/index.ts
packages/app/src/offscreen/Offscreen.ts
packages/app/src/offscreen/__tests__/offscreenController.test.ts
packages/app/src/offscreen/index.ts
packages/app/src/offscreen/mocks.ts
packages/app/src/ui/components/VerifiableCredential/Display/__tests__/VerifiableCredentialDisplay.test.tsx
packages/app/src/ui/components/VerifiableCredential/Item/VerifiableCredentialItem.tsx
packages/app/src/ui/components/VerifiableCredential/Item/__tests__/VerifiableCredentialItem.test.tsx
packages/app/src/ui/components/VerifiableCredential/Item/__tests__/useVerifiableCredentialItem.test.ts
packages/app/src/ui/components/VerifiableCredential/Item/useVerifiableCredentialItem.ts
packages/app/src/ui/ducks/__tests__/verifiableCredentials.test.tsx
packages/app/src/ui/ducks/verifiableCredentials.ts
packages/app/src/ui/hooks/verifiableCredentials/__tests__/useCryptkeeperVerifiableCredentials.test.tsx
packages/app/src/ui/hooks/verifiableCredentials/useCryptkeeperVerifiableCredentials.ts
packages/app/src/ui/pages/AddVerifiableCredential/__tests__/AddVerifiableCredential.test.tsx
packages/app/src/ui/pages/AddVerifiableCredential/__tests__/useAddVerifiableCredential.test.ts
packages/app/src/ui/pages/AddVerifiableCredential/useAddVerifiableCredential.ts
packages/app/src/ui/pages/PresentVerifiableCredential/usePresentVerifiableCredential.ts
packages/app/src/util/__tests__/credentials.test.ts
packages/app/src/util/credentials.ts

This PR adds missing tests for the extension
Blocked by #1037 
N/A
N/A

test: add missing tests for the extension

---

packages/app/src/background/cryptKeeper.ts
packages/app/src/background/services/approval/index.ts
packages/app/src/background/services/injector/Injector.ts
packages/app/src/background/services/injector/InjectorHandler.ts
packages/app/src/background/services/injector/__tests__/injector.test.ts
packages/app/src/background/services/injector/types.ts
packages/app/src/background/services/protocol/ProtocolService.ts
packages/app/src/background/services/protocol/__tests__/protocol.test.ts
packages/app/src/background/services/protocol/index.ts
packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
packages/app/src/constants/rpcInternalActions.ts
packages/app/src/offscreen/Offscreen.ts
packages/app/src/offscreen/__tests__/offscreenController.test.ts
packages/e2e/pages/cryptKeeper/Groups.ts
packages/types/src/approval/index.ts
packages/types/src/index.ts

This PR refactors injector service and adds protocol service for proof generation.
Related to #945 
N/A
N/A

refactor: add protocol service
