CryptKeeperZK/crypt-keeper-extension

src/background/services/identity.ts
Resolving the bug of not being able to get the active identity once the user pops-up the CK extension. Now, the last activated identity commitment from the user is being encrypted and stored in chrome storage, 
What is missing: 
Fix #84 
N/A
N/A
N/A
- Follow how to install the extension in your Chrome browser from the README. 
- Create a new Identity if you haven't already.
- Run the demo app (Checkout Readme).
- Then the app will be able to connect to CK and read the current active identity. 
=> fix: resolving getActiveIdentity bug issue #84

demo/index.tsx, demo/package-lock.json, demo/package.json, package-lock.json, package.json, scripts/mock-merkle-proof.ts, src/background/backgroundPage.ts, src/background/services/lock.ts, src/background/services/protocols/rln.ts, src/background/services/protocols/semaphore.ts, src/background/services/zk-validator.ts, src/background/zk-keeper.ts, src/contentscripts/injected.ts, src/contentscripts/proof/index.ts, src/contentscripts/proof/semaphore.ts, src/ui/popup.tsx, src/util/constants.ts
There is an issue with proof generation because `ffjavascript` in `snarkjs` package creates web workers.
For now it's not supported yet in Manifest V3 to spawn web workers from service worker.
As a solution, I moved semaphore proof generation to content script side to not lose the worker scope.  
Details are bellow:
Fixes #89
N/A
1. Complete all steps in readme for demo launch
2. Connect with CK extension
3. Try to generate semaphore proof
4. You will see a success message that proof was generated
=> fix: semaphore proof generation

src/ui/pages/Home/index.tsx
Just hide activity tab on main screen because we don't have activity data.
Fixes #97 
Just open extension popup and there must be only "Identities" tab.
=> fix: hide activity tab

src/background/zk-keeper.ts, src/types/index.ts, src/ui/components/ConfirmRequestModal/index.tsx
Currently, there is no approve step for RLN proof generation.
This PR has the same changes as Semaphore.
Closes #91
N/A
1. Reinstall extension to reset approve flag
2. Launch demo
3. Don't approve all request from demo website
4. Try to generate RLN proof
5. You'll see approve step
6. Approve/Reject buttons works as expected
=> feat: add approve step for rln proof generation

demo/index.tsx, src/contentScripts/injected.ts
Sometimes zkpr is not defined and it's related to wrong usage of global variable.
Closes #102
N/A
1. Run demo and try to reload page to catch if zkpr is not defined
=> fix: zkpr initialization for demo

src/background/services/__tests__/identityService.test.ts, src/background/services/identity.ts, src/background/services/simpleStorage.ts, src/background/zkKeeper.ts, src/setupTests.ts, src/ui/ducks/identities.ts, src/ui/pages/Home/home.scss, src/ui/pages/Home/index.tsx, src/util/constants.ts, tsconfig.json
This PR adds support for removing all the identities and setting active identity when removing.
Closes #27 
N/A
1. Reinstall extension
2. Create identities
3. Try to delete all of them
=> feat: delete all identities

README.md, src/background/services/__tests__/identityService.test.ts, src/background/services/__tests__/notificationService.test.ts, src/background/services/identity.ts, src/background/services/notification.ts, src/manifest.json, src/setupTests.ts
This PR adds Notification service and notification for generated identity.
Notification service uses rich notification api.
Closes #33 
N/A
Try to create new identity and see a notification with identity commitment
=> feat: add notifications service and permission

src/ui/components/ConfirmRequestModal/confirm-modal.scss, src/ui/components/FullModal/full-modal.scss, src/ui/pages/Popup/popup.scss
Currently, there is an issue with scaling (extension styles lost proportions).
This PR is supposed to fix this issue by changing global popup styles.
Closes #106
Scale x1.5
Scale x1
Scale x1.5
1. Install extension
2. Try to change Scale in display settings
3. Check popup proportions
=> fix: popup window size

src/config/mock/modal.ts, src/setupTests.ts, src/types/index.ts, src/ui/components/Checkbox/index.tsx, src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/ConnectionApprovalModal.tsx, src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/__tests__/ConnectionApprovalModal.test.tsx, src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/__tests__/useConnectionApprovalModal.test.ts, src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/index.ts, src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/useConnectionApprovalModal.ts, src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/DefaultApprovalModal.tsx, src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/__tests__/DefaultApprovalModal.test.tsx, src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/index.ts, src/ui/components/ConfirmRequestModal/components/ProofModal/ProofModal.tsx, src/ui/components/ConfirmRequestModal/components/ProofModal/__tests__/ProofModal.test.tsx, src/ui/components/ConfirmRequestModal/components/ProofModal/__tests__/useProofModal.test.ts, src/ui/components/ConfirmRequestModal/components/ProofModal/index.ts, src/ui/components/ConfirmRequestModal/components/ProofModal/useProofModal.ts, src/ui/components/ConfirmRequestModal/components/index.ts, src/ui/components/ConfirmRequestModal/index.tsx, src/ui/components/ConnectionModal/index.tsx, src/ui/hooks/wallet/__tests__/useWallet.test.ts, src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx, src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx, src/ui/pages/Home/components/Info/__tests__/Info.test.tsx, src/util/__tests__/postMessage.test.ts
This PR moves request modals to separate components with refactoring and tests.
This is a part of PR #183
Related to #140 
Related to #181 
Blocked by #183 
N/A
N/A
=> refactor: request modals

jest.config.json, src/background/services/__tests__/identityService.test.ts, src/background/services/identity.ts
This PR fixes issue when user tries to delete non-active identity and active identity switches to a default one.
Closes #180
Blocked by #189 
N/A
1. Try to delete non-active identity
2. Check the active identity is the same as before the removing
=> fix: prevent changing active identity

src/background/controllers/__tests__/browserUtils.test.ts, src/background/controllers/__tests__/handler.test.ts, src/background/controllers/__tests__/requestManager.test.ts, src/background/controllers/browserUtils.ts, src/background/controllers/handler.ts, src/background/controllers/requestManager.ts, src/setupTests.ts, src/types/index.ts, src/ui/components/ConfirmRequestModal/__tests__/useConfirmRequestModal.test.ts, src/ui/components/ConfirmRequestModal/useConfirmRequestModal.ts, src/util/__tests__/pushMessage.test.ts
This PR adds tests for background controllers: `BrowserUtils`, `RequestManager` and `Handler`.
N/A
N/A
N/A
=> test: add tests for background controllers

jest.config.json, package-lock.json, package.json, src/background/backgroundPage.ts, src/background/controllers/browserUtils.ts, src/background/services/__tests__/identityService.test.ts, src/background/services/identity.ts, src/config/mock/wallet.ts, src/ui/components/ConfirmRequestModal/__tests__/ConfirmRequestModal.test.tsx, src/ui/components/Header/__tests__/Header.test.tsx, src/ui/components/Header/index.tsx, src/ui/components/Icon/index.tsx, src/ui/components/Input/index.tsx, src/ui/components/Input/input.scss, src/ui/components/Menuable/Menuable.tsx, src/ui/hooks/validation/__tests__/useValidationResolver.test.ts, src/ui/hooks/validation/index.ts, src/ui/hooks/wallet/__tests__/useWallet.test.ts, src/ui/hooks/wallet/index.ts, src/ui/pages/Home/Home.tsx, src/ui/pages/Home/__tests__/Home.test.tsx, src/ui/pages/Home/__tests__/useHome.test.ts, src/ui/pages/Home/useHome.ts, src/ui/pages/Onboarding/Onboarding.tsx, src/ui/pages/Onboarding/__tests__/Onboarding.test.tsx, src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts, src/ui/pages/Onboarding/onboarding.scss, src/ui/pages/Onboarding/useOnboarding.ts
This PR adds password strength rules for onboarding page and some testing chores.
Closes #191
Blocked by #200 
N/A
1. Go to onboarding page
2. Try to check different types and combinations of passwords and then submit the form
3. Check validation messages
=> feat: add validation for onboarding page

demo/index.tsx, demo/package-lock.json, demo/package.json, src/background/services/__tests__/identityService.test.ts, src/background/services/identity.ts, src/background/zkKeeper.ts, src/constants/rpcActions.ts, src/contentScripts/index.ts, src/contentScripts/injected.ts, src/setupTests.ts, src/ui/ducks/__tests__/identities.test.tsx, src/ui/ducks/identities.ts, src/ui/popup.tsx
In case of connecting to Zkitter, it needs to be able to know the Active Identity web2 proivder option. Because depending on that value, Zkitter will redirect the user to the right web2 provider the user choose before in CK, and that will allow the user easily create a Proof of Reputation using Zkitter.
N/A
N/A
N/A
N/A
=> chore: get active identity data (commitment + web2provider)

jest.config.json, src/popup.html, src/setupTests.ts, src/ui/components/Menuable/Menuable.tsx, src/ui/ducks/__tests__/app.test.tsx, src/ui/ducks/__tests__/hooks.test.ts, src/ui/ducks/__tests__/identities.test.tsx, src/ui/ducks/__tests__/permissions.test.tsx, src/ui/ducks/__tests__/requests.test.tsx, src/ui/pages/Home/Home.tsx, src/ui/pages/Home/__tests__/Home.test.tsx, src/ui/pages/Home/__tests__/useHome.test.ts, src/ui/pages/Home/components/IdentityList/IdentityList.tsx, src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx, src/ui/pages/Home/components/TabList/TabList.tsx, src/ui/pages/Home/components/TabList/__tests__/TabList.test.tsx, src/ui/pages/Home/components/TabList/tabListStyles.scss, src/ui/pages/Home/useHome.ts, src/ui/popup.tsx, src/ui/services/provider/index.ts, src/ui/theme.ts
This PR adds support for material-ui theme and "Activity" tab is back again (empty yet).
Related to #30 
1. Go to home page
2. Try to switch tabs
3. Try to delete all the identities
=> feat: return activity tab back

jest.config.json, package-lock.json, package.json, src/background/services/history/__tests__/history.test.ts, src/background/services/history/index.ts, src/background/zkKeeper.ts, src/config/mock/nanoidMock.js, src/constants/rpcActions.ts, src/types/index.ts, src/ui/ducks/__tests__/identities.test.tsx, src/ui/ducks/identities.ts
This PR adds support for removing operation and history incognito mode.
Blocked by #252 
Related to #30
N/A
N/A
N/A
=> feat: remove history operation

.github/workflows/e2e.yml, demo/index.tsx, e2e/fixtures/index.ts, e2e/helpers/account.ts, e2e/pages/BasePage.ts, e2e/pages/CryptKeeper.ts, e2e/pages/index.ts, e2e/tests/identity.test.ts, e2e/tests/initialization.test.ts, playwright.config.ts, src/background/services/identity.ts, src/ui/pages/Home/components/IdentityList/Item/index.tsx
This PR adds e2e tests for identity operations
Related to #237 
N/A
N/A
N/A
=> test: add e2e tests for identities

e2e/fixtures/index.ts, e2e/helpers/account.ts, e2e/pages/cryptKeeper/Activity.ts, e2e/pages/cryptKeeper/CryptKeeper.ts, e2e/pages/cryptKeeper/Identities.ts, e2e/pages/cryptKeeper/Settings.ts, e2e/pages/cryptKeeper/index.ts, e2e/pages/index.ts, e2e/tests/identity.test.ts, src/ui/pages/Home/components/ActivityList/Item/ActivityListItem.tsx
This PR adds e2e tests for activity tab and for settings page.
Related to #237 
Blocked by #265 
N/A
N/A
N/A
=> test: add e2e tests for history operations

src/ui/pages/DownloadBackup/__tests__/useDownloadBackup.test.ts, src/ui/pages/DownloadBackup/useDownloadBackup.ts, src/util/__tests__/browser.test.ts, src/util/browser.ts
This PR adds support for dowloading backup json file.
Related to #257 
N/A
1. Enable `BACKUP` flag
2. Go to advanced settings and click download backup
3. Enter password and dowload
4. See backup file is downloaded
=> feat: add download backup file

package-lock.json, package.json, src/background/services/key/__tests__/keyStorageService.test.ts, src/background/services/key/index.ts, src/background/services/key/types.ts, src/background/services/mnemonic/__tests__/mnemonic.test.ts, src/background/services/mnemonic/index.ts, webpack.common.js
This PR adds support for bip39 mnemonic phrase generation and key storage service.
This is a part of #333.
Closes #339 
Closes #342 
N/A
N/A
=> feat: add key storage service

.github/CODEOWNERS, src/constants/paths.ts, src/setupTests.ts, src/ui/components/RevealMnemonicInput/RevealMnemonicInput.tsx, src/ui/components/RevealMnemonicInput/__tests__/RevealMnemonicInput.test.tsx, src/ui/components/RevealMnemonicInput/__tests__/useRevealMnemonic.test.ts, src/ui/components/RevealMnemonicInput/index.ts, src/ui/components/RevealMnemonicInput/useRevealMnemonic.ts, src/ui/hooks/timeout/__tests__/useTimeout.test.ts, src/ui/hooks/timeout/index.ts, src/ui/pages/Mnemonic/Mnemonic.tsx, src/ui/pages/Mnemonic/__tests__/Mnemonic.test.tsx, src/ui/pages/Mnemonic/__tests__/useMnemonic.test.ts, src/ui/pages/Mnemonic/index.ts, src/ui/pages/Mnemonic/useMnemonic.ts, src/ui/pages/Popup/Popup.tsx, src/util/__tests__/browser.test.ts, src/util/browser.ts
This PR adds ui page without integration as a part of BIP39 integration.
Closes #338 
There is no integration right now so only ui can be tested.
1. Open extension in a separate window
2. Go to `/mnemonic` page
3. Check copy and download buttons
4. `Get started` button will redirect to home
=> feat: mnemonic ui

demo/index.tsx, e2e/pages/cryptKeeper/Identities.ts, e2e/tests/backup.test.ts, e2e/tests/identity.test.ts, e2e/tests/proofGeneration.test.ts, jest.config.json, src/background/appInit.ts, src/background/controllers/requestManager.ts, src/background/services/zkIdentity/__test__/zkIdentity.test.ts, src/background/services/zkIdentity/index.ts, src/config/mock/wallet.ts, src/connectors/mock.ts, src/providers/sdk/Base.ts, src/ui/components/Icon/index.tsx, src/ui/components/Menuable/MenuItem.tsx, src/ui/components/Menuable/Menuable.tsx, src/ui/components/Menuable/menuable.scss, src/ui/components/Menuable/useMenuable.ts, src/ui/components/Modal/index.tsx, src/ui/ducks/identities.ts, src/ui/pages/CreateIdentity/CreateIdentity.tsx, src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx, src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts, src/ui/pages/CreateIdentity/useCreateIdentity.ts, src/ui/pages/Home/components/IdentityList/IdentityList.tsx, src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx, src/ui/pages/Home/components/IdentityList/identityListStyles.scss
This PR adds support for identity creation with cryptkeeper keys and metamask.
Blocked by #372
Closes #341 
1. Create new account which has seed phrase 
2. Go to create identity screen
3. Try to create identity with cryptkeeper or metamask
=> feat: support cryptkeeper identity creation

demo/index.tsx, demo/types.ts, demo/useCryptKeeper.ts, src/background/contentScript.ts, src/config/chains.ts, src/config/mock/wallet.ts, src/config/rpc.ts, src/connectors/__tests__/cryptKeeper.test.ts, src/connectors/__tests__/mock.test.ts, src/connectors/__tests__/utils.test.ts, src/connectors/cryptKeeper.ts, src/connectors/index.ts, src/connectors/utils.ts, src/providers/sdk/Base.ts, src/types/config/index.ts, src/types/hooks/index.ts, src/types/index.ts, src/ui/hooks/wallet/__tests__/useCryptKeeperWallet.test.ts, src/ui/hooks/wallet/__tests__/useEthWallet.test.ts, src/ui/hooks/wallet/index.ts, src/ui/hooks/wallet/useCryptKeeper.ts, src/ui/hooks/wallet/useEthWallet.ts, src/ui/pages/Home/components/Info/Info.tsx, src/ui/pages/Home/useHome.ts, src/ui/pages/Popup/__tests__/usePopup.test.ts, src/ui/pages/Popup/usePopup.ts
This PR adds address integration for cryptkeeper.
Related to #377 
N/A
N/A
=> feat: web3-react bip39

e2e/pages/cryptKeeper/CryptKeeper.ts, src/config/mock/wallet.ts, src/types/hooks/index.ts, src/ui/components/AccountMenu/AccountMenu.tsx, src/ui/components/AccountMenu/__tests__/AccountMenu.test.tsx, src/ui/components/AccountMenu/__tests__/useAccountMenu.test.ts, src/ui/components/AccountMenu/index.ts, src/ui/components/AccountMenu/useAccountMenu.ts, src/ui/components/Header/__tests__/Header.test.tsx, src/ui/components/Header/index.tsx, src/ui/hooks/wallet/__tests__/useCryptKeeperWallet.test.ts, src/ui/hooks/wallet/__tests__/useEthWallet.test.ts, src/ui/hooks/wallet/useCryptKeeper.ts, src/ui/hooks/wallet/useEthWallet.ts, src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx, src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts, src/ui/pages/CreateIdentity/useCreateIdentity.ts, src/ui/pages/DownloadBackup/__tests__/DownloadBackup.test.tsx, src/ui/pages/Home/__tests__/Home.test.tsx, src/ui/pages/Popup/__tests__/Popup.test.tsx, src/ui/pages/Settings/__tests__/Settings.test.tsx, src/ui/theme.ts
This PR adds ui support for multiple accounts.
Blocked by #417
Related to #377 
1. Reinstall the extension
2. Complete onboarding
3. Create identity
4. Check identity field has the same address as in account menu
=> feat: account menu

demo/useCryptKeeper.ts, package-lock.json, src/background/contentScript.ts, src/background/cryptKeeper.ts, src/background/services/event/types.ts, src/background/services/wallet/__tests__/walletService.test.ts, src/background/services/wallet/index.ts, src/constants/rpcActions.ts, src/providers/sdk/Base.ts, src/setupTests.ts, src/ui/components/AccountMenu/AccountMenu.tsx, src/ui/components/AccountMenu/__tests__/AccountMenu.test.tsx, src/ui/components/AccountMenu/__tests__/useAccountMenu.test.ts, src/ui/components/AccountMenu/useAccountMenu.ts, src/ui/ducks/__tests__/app.test.tsx, src/ui/ducks/app.ts, src/ui/pages/CreateIdentity/useCreateIdentity.ts, src/ui/pages/Home/Home.tsx, src/ui/pages/Home/__tests__/Home.test.tsx, src/ui/pages/Home/__tests__/useHome.test.ts, src/ui/pages/Home/components/IdentityList/identityListStyles.scss, src/ui/pages/Home/components/Info/Info.tsx, src/ui/pages/Home/components/Info/__tests__/Info.test.tsx, src/ui/pages/Home/useHome.ts, src/ui/pages/Popup/__tests__/usePopup.test.ts, src/ui/pages/Popup/usePopup.ts
This PR adds support for switching cryptkeeper addresses.
Closes #377 
Closes #333
Blocked by #418
N/A
=> feat: switch account

e2e/pages/cryptKeeper/Identities.ts, src/background/services/zkIdentity/__test__/factory.test.ts, src/background/services/zkIdentity/factory/index.ts, src/background/services/zkIdentity/index.ts, src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts, src/ui/pages/CreateIdentity/useCreateIdentity.ts, src/ui/pages/Home/components/IdentityList/Item/index.tsx, src/ui/pages/Home/components/IdentityList/__tests__/IdentityItem.test.tsx
This PR adds support for adding signing account for random identities
Related to #333 
N/A
1. Try to create identity with metamask and cryptkeeper
2. See address is appeared for random identities 
=> feat: associate random identity with user address

package-lock.json, package.json, src/setupTests.ts, src/ui/components/Dropdown/__tests__/Dropdown.test.tsx, src/ui/components/IdentityList/IdentityList.tsx, src/ui/components/IdentityList/Item/index.tsx, src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx, src/ui/components/IdentityList/__tests__/IdentityList.test.tsx, src/ui/components/IdentityList/identityListStyles.scss, src/ui/ducks/__tests__/identities.test.tsx, src/ui/ducks/identities.ts, src/ui/pages/ConnectIdentity/ConnectIdentity.tsx, src/ui/pages/ConnectIdentity/__tests__/ConnectedIdentity.test.tsx, src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts, src/ui/pages/ConnectIdentity/useConnectIdentity.ts, src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx, src/ui/popup.tsx, src/ui/theme.ts
This PR adds support for linked and unlinked identities and is a part of #445.
Blocked by #467
N/A
N/A
=> feat: connect identity integration ui 

src/background/services/zkIdentity/factory/index.ts, src/background/services/zkIdentity/index.ts, src/ui/components/IdentityList/IdentityList.tsx, src/ui/ducks/__tests__/identities.test.tsx, src/ui/ducks/identities.ts, src/ui/pages/ConnectIdentity/ConnectIdentity.tsx, src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts, src/ui/pages/ConnectIdentity/useConnectIdentity.ts, src/ui/pages/CreateIdentity/CreateIdentity.tsx, src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx, src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts, src/ui/pages/CreateIdentity/useCreateIdentity.ts
This PR is a part of #445 adds support for creating identities from connect screen.
Blocked by #450
Blocked by #474
N/A
N/A
=> feat: create identity from connect screen

LICENSE, demo/index.tsx, demo/types.ts, demo/useCryptKeeper.ts, manifest.chrome.json, manifest.firefox.json, src/background/contentScript.ts, src/background/controllers/browserUtils.ts, src/background/cryptKeeper.ts, src/background/services/zkIdentity/__test__/zkIdentity.test.ts, src/background/services/zkIdentity/index.ts, src/constants/rpcActions.ts, src/providers/sdk/Base.ts, src/types/duck/identities.ts, src/types/identity/index.ts, src/ui/components/IdentityList/IdentityList.tsx, src/ui/ducks/__tests__/identities.test.tsx, src/ui/ducks/identities.ts, src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts, src/ui/pages/ConnectIdentity/useConnectIdentity.ts, src/ui/pages/Home/Home.tsx, src/ui/pages/Home/__tests__/useHome.test.ts, src/ui/pages/Home/useHome.ts, src/ui/pages/Popup/__tests__/usePopup.test.ts, src/ui/pages/Popup/usePopup.ts, webpack.common.js
This PR is a part of #445 adds support for identity host connection with demo host.
1. Check identities created from demo have host in metadata. 
2. Check create identity page is open properly from extension
=> feat: demo host connection

demo/index.tsx, e2e/tests/identity.test.ts, src/ui/components/IdentityList/Item/index.tsx, src/ui/components/IdentityList/__tests__/IdentityList.test.tsx, src/ui/pages/Settings/Settings.tsx
This PR is a part of #445 adds support for removing identities on demo and restricts deleting connected identities.
Blocked by #490 
1. Connected identity can't be removed from identity list
2. After all identity removal from advanced settings page, demo page shows no connected identity screen.
=> feat: delete connected identity

e2e/tests/backup.test.ts, e2e/tests/identity.test.ts, e2e/tests/initialization.test.ts, e2e/tests/proofGeneration.test.ts, src/background/services/zkIdentity/__test__/zkIdentity.test.ts, src/background/services/zkIdentity/index.ts, src/connectors/__tests__/cryptKeeper.test.ts, src/connectors/__tests__/utils.test.ts, src/connectors/cryptKeeper.ts, src/connectors/index.ts, src/connectors/utils.ts, src/types/hooks/index.ts, src/types/identity/index.ts, src/ui/components/AccountMenu/AccountMenu.tsx, src/ui/components/AccountMenu/__tests__/AccountMenu.test.tsx, src/ui/components/AccountMenu/__tests__/useAccountMenu.test.ts, src/ui/components/AccountMenu/useAccountMenu.ts, src/ui/components/Header/__tests__/Header.test.tsx, src/ui/components/Header/index.tsx, src/ui/hooks/wallet/__tests__/useCryptKeeperWallet.test.ts, src/ui/hooks/wallet/useCryptKeeper.ts, src/ui/hooks/wallet/useEthWallet.ts, src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx, src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts, src/ui/pages/CreateIdentity/useCreateIdentity.ts
This PR adds support for displaying current connector.
1. Connect with metamask
2. See "Connected to Metamask" label in header
=> feat: metamask connection indicator

manifest.chrome.json, manifest.firefox.json, package.json, pnpm-lock.yaml, src/background/appInit.ts, src/background/backgroundPage.ts, src/background/contentScript.ts, src/background/controllers/__tests__/browserUtils.test.ts, src/background/controllers/browserUtils.ts, src/background/services/backup/BackupService.ts, src/background/services/history/index.ts, src/background/services/injector/__tests__/injector.test.ts, src/background/services/injector/index.ts, src/background/services/lock/__tests__/lockerService.test.ts, src/background/services/lock/index.ts, src/background/services/notification/__tests__/notificationService.test.ts, src/background/services/notification/index.ts, src/background/services/storage/__tests__/simpleStorage.test.ts, src/background/services/storage/index.ts, src/background/services/zkIdentity/__test__/zkIdentity.test.ts, src/background/services/zkIdentity/index.ts, src/setupTests.ts, src/ui/popup.tsx, src/ui/services/provider/index.ts, src/util/__tests__/browser.test.ts, src/util/__tests__/postMessage.test.ts, src/util/__tests__/pushMessage.test.ts, src/util/browser.ts, src/util/postMessage.ts, src/util/pushMessage.ts
This PR fixes firefox launch issue. However, user still needs to allow permissions on firefox extension settings to make cryptkeeper work. This is because host permissions in firefox are optional. 
Closes #500 
N/A
Can launch in firefox
=> fix: firefox launch

packages/app/package.json, packages/app/webpack.prod.js, pnpm-lock.yaml
Optimizing webpack prod bundle size, by using `splitChunks` and `TerserPlugin` together. 
N/A
N/A
N/A
=> chore: optimize webpack prod

packages/app/src/connectors/__tests__/cryptKeeper.test.ts, packages/app/src/connectors/cryptKeeper.ts, packages/app/src/setupTests.ts, packages/demo/useCryptKeeper.ts, packages/providers/README.md, packages/providers/src/constants/index.ts, packages/providers/src/event/EventEmitter.ts, packages/providers/src/event/index.ts, packages/providers/src/event/types.ts, packages/providers/src/index.ts, packages/providers/src/sdk/CryptKeeperInjectedProvider.ts, packages/providers/src/sdk/index.ts, packages/providers/src/sdk/initializeInjectedProvider.ts, packages/providers/src/sdk/utils.ts
This PR adds enhancements to `@cryptkeeperzk/providers` package to make it simpler to integrate with applications. 
* Related #92 
* Enhances #557 
* Enhances #540 
N/A
N/A
=> feat: enhance cryptkeeperzk/provider

packages/app/src/background/services/approval/__tests__/approvalService.test.ts, packages/app/src/background/services/approval/index.ts, packages/app/src/background/services/crypto/__tests__/crypto.test.ts, packages/app/src/background/services/crypto/index.ts, packages/app/src/background/services/history/__tests__/history.test.ts, packages/app/src/background/services/history/index.ts, packages/app/src/background/services/lock/__tests__/lockerService.test.ts, packages/app/src/background/services/lock/index.ts, packages/app/src/background/services/wallet/__tests__/walletService.test.ts, packages/app/src/background/services/wallet/index.ts, packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts, packages/app/src/background/services/zkIdentity/index.ts
This PR moves crypto logic from lock service to a separate one to support encrypt/decrypt with mnemonic phrase. 
Related to #585 
Blocked by #584 
N/A
N/A
=> refactor: move crypto logic from lock service

packages/app/jest.config.js, packages/app/src/background/services/wallet/__tests__/walletService.test.ts, packages/app/src/background/services/wallet/index.ts, packages/app/src/ui/components/MnemonicInput/MnemonicInput.tsx, packages/app/src/ui/ducks/app.ts, packages/app/src/ui/hooks/validation/__tests__/useValidationResolver.test.ts, packages/app/src/ui/hooks/validation/index.ts, packages/app/src/ui/pages/GenerateMnemonic/GenerateMnemonic.tsx, packages/app/src/ui/pages/GenerateMnemonic/__tests__/GenerateMnemonic.test.tsx, packages/app/src/ui/pages/GenerateMnemonic/__tests__/useGenerateMnemonic.test.ts, packages/app/src/ui/pages/GenerateMnemonic/useGenerateMnemonic.ts, packages/app/src/ui/pages/Recover/__tests__/useRecover.test.ts, packages/app/src/ui/pages/Recover/useRecover.ts, packages/e2e/helpers/account.ts, packages/e2e/pages/cryptKeeper/CryptKeeper.ts, packages/e2e/pages/cryptKeeper/Recover.ts, packages/e2e/tests/recover.test.ts
This PR adds support for creating cryptkeeper account with user defined mnemonic.
Closes #575 
Closes #381 
1. Reinstall the extension
2. Create account with generated mnemonic and with user defined mnemonic
3. Check reveak mnemonic page has the same mnemonic
=> feat: onboarding with user mnemonic

packages/app/src/background/backgroundPage.ts, packages/app/src/background/controllers/__tests__/handler.test.ts, packages/app/src/background/controllers/handler.ts, packages/app/src/background/cryptKeeper.ts, packages/app/src/ui/components/PermissionModal/PermissionModal.tsx, packages/app/src/util/__tests__/browser.test.ts, packages/app/src/util/browser.ts
This PR adds access control for rpc controller which cuts all the unauthorized calls from outside.
Blocked by #627 
N/A
Try to call any method from provider which doesn't have bypass setting. 
=> feat: add rpc access for controller

packages/app/src/background/services/wallet/index.ts, packages/app/src/ui/components/UploadInput/UploadInput.tsx, packages/app/src/ui/ducks/__tests__/backup.test.ts, packages/app/src/ui/ducks/backup.ts, packages/app/src/ui/pages/UploadBackup/UploadBackup.tsx, packages/app/src/ui/pages/UploadBackup/__tests__/useUploadBackup.test.ts, packages/app/src/ui/pages/UploadBackup/useUploadBackup.ts, packages/app/src/util/__tests__/file.test.ts, packages/app/src/util/file.ts
This PR adds integration between backup upload screen and background scripts.
Blocked by #650
Closes #331 
N/A
N/A
=> feat: backup upload integration

packages/app/src/background/cryptKeeper.ts, packages/app/src/background/services/backup/BackupService.ts, packages/app/src/background/services/backup/__tests__/BackupService.test.ts, packages/app/src/background/services/history/index.ts, packages/app/src/background/services/lock/__tests__/lockerService.test.ts, packages/app/src/background/services/lock/index.ts, packages/app/src/background/services/wallet/index.ts, packages/app/src/constants/paths.ts, packages/app/src/ui/components/Button/index.tsx, packages/app/src/ui/ducks/__tests__/backup.test.ts, packages/app/src/ui/ducks/backup.ts, packages/app/src/ui/pages/Login/Login.tsx, packages/app/src/ui/pages/Login/login.scss, packages/app/src/ui/pages/Onboarding/Onboarding.tsx, packages/app/src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts, packages/app/src/ui/pages/Onboarding/useOnboarding.ts, packages/app/src/ui/pages/OnboardingBackup/OnboardingBackup.tsx, packages/app/src/ui/pages/OnboardingBackup/__tests__/OnboardingBackup.test.tsx, packages/app/src/ui/pages/OnboardingBackup/__tests__/useOnboardingBackup.test.ts, packages/app/src/ui/pages/OnboardingBackup/index.ts, packages/app/src/ui/pages/OnboardingBackup/useOnboardingBackup.ts, packages/app/src/ui/pages/Popup/Popup.tsx, packages/app/src/ui/pages/Popup/usePopup.ts, packages/providers/src/constants/rpcAction.ts
This PR adds support for uploading backup file as a part of onboarding flow.
Blocked by #664
Related to #330 
1. Install the extension
2. Create new account
3. Create some identities, generate some proofs from demo
4. Download backup file
5. Delete and install the extension again
6. Try to upload backup file from onboarding flow
7. Check the accounts, identities and all data related
=> feat: backup onboarding flow 😈

packages/app/src/background/services/injector/__tests__/injector.test.ts, packages/app/src/background/services/injector/index.ts, packages/app/src/background/shared/__tests__/utils.test.ts, packages/app/src/background/shared/utils.ts, packages/app/src/constants/index.ts, packages/app/src/constants/paths.ts, packages/app/src/manifest/v2/manifest.firefox.json, packages/app/src/offscreen/Offscreen.ts, packages/app/src/ui/components/IdentityList/Item/index.tsx, packages/app/src/ui/components/IdentityList/Item/useIdentityItem.ts, packages/app/src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx, packages/app/src/ui/components/IdentityList/__tests__/IdentityList.test.tsx, packages/app/src/ui/ducks/__tests__/identities.test.tsx, packages/app/src/ui/ducks/identities.ts, packages/app/src/ui/hooks/url/__tests__/useUrlParam.test.ts, packages/app/src/ui/hooks/url/index.ts, packages/app/src/ui/pages/Identity/Identity.tsx, packages/app/src/ui/pages/Identity/__tests__/Idenity.test.tsx, packages/app/src/ui/pages/Identity/__tests__/useIdentityPage.test.ts, packages/app/src/ui/pages/Identity/index.ts, packages/app/src/ui/pages/Identity/useIdentityPage.ts, packages/app/src/ui/pages/Popup/Popup.tsx, packages/app/src/util/__tests__/browser.test.ts, packages/app/src/util/browser.ts, packages/e2e/.eslintignore, packages/e2e/pages/cryptKeeper/Identities.ts, packages/e2e/tests/identity.test.ts
This PR adds identity page to show user full identity metadata.
Closes #683 
Extended mode:
Popup mode:
1. Go to home
2. Open identity view
3. See identity metadata
=> feat: identity page

packages/app/src/background/contentScript.ts, packages/app/src/background/cryptKeeper.ts, packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts, packages/app/src/background/services/zkIdentity/index.ts, packages/app/src/ui/components/FullModal/fullModal.scss, packages/app/src/ui/components/IdentityList/IdentityList.tsx, packages/app/src/ui/components/IdentityList/Item/index.tsx, packages/app/src/ui/ducks/__tests__/identities.test.tsx, packages/app/src/ui/ducks/identities.ts, packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx, packages/app/src/ui/pages/Home/components/ActivityList/Item/activityListItemStyles.scss, packages/app/src/ui/pages/Home/components/ActivityList/activityListStyles.scss, packages/demo/index.tsx, packages/demo/useCryptKeeper.ts, packages/providers/src/constants/rpcAction.ts, packages/providers/src/sdk/CryptKeeperInjectedProvider.ts, packages/types/src/duck/identities.ts, packages/types/src/identity/index.ts
This PR hides identity commitment and keeps it only inside the extension.
Related to #313 
1. Identity commitment can't be retried outside the extension
=> feat: hide identity commitment

packages/app/src/background/contentScript.ts, packages/app/src/background/services/credentials/index.ts, packages/app/src/connectors/__tests__/cryptKeeper.test.ts, packages/app/src/connectors/cryptKeeper.ts, packages/demo/useCryptKeeper.ts, packages/providers/src/event/index.ts, packages/providers/src/event/types.ts, packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
As discussed [here](https://github.com/CryptKeeperZK/crypt-keeper-extension/pull/674#discussion_r1295363554), it would be nice to have explicit event names to avoid potential typos or mismatches when emitting/receiving events. We make `EventName` an enum and change all magic string event names to use the new EventName. 
=> chore: make EventName an enum (#738)

.github/workflows/release.yml
Disable commit singing
N/A
N/A
=> fix: disable commit signing for release bot

.github/workflows/publishChrome.yml, .github/workflows/publishFirefox.yml, .github/workflows/publishPackages.yml, .github/workflows/release.yml
Use PAT instead of GITHUB_TOKEN in release workflow
Related to #675
N/A
N/A
=> fix: use pat instead of github token

packages/demo/index.tsx, packages/e2e/tests/revealIdentityCommitment.test.ts
Fixes e2e tests for reveal identity and added url params flags.
Related to #849
N/A
N/A
=> fix: e2e tests

packages/app/src/background/cryptKeeper.ts, packages/app/src/background/services/group/GroupService.ts, packages/app/src/background/services/group/__tests__/GroupService.test.ts, packages/app/src/background/services/group/index.ts, packages/app/src/background/services/injector/Injector.ts, packages/app/src/background/services/injector/InjectorHandler.ts, packages/app/src/background/services/injector/__tests__/injector.test.ts, packages/app/src/constants/rpcInternalActions.ts, packages/providers/src/constants/rpcExternalAction.ts, packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
In this PR changes includes protecting the group Bandada APIs. 
- Fixes #899 
N/A
- Please check Bandada function from the Demo.
=> fix: protect external bandada apis

packages/app/src/background/cryptKeeper.ts, packages/app/src/background/services/approval/__tests__/approvalService.test.ts, packages/app/src/background/services/approval/index.ts, packages/app/src/background/services/base/Base.ts, packages/app/src/background/services/injector/Injector.ts, packages/app/src/background/services/injector/InjectorHandler.ts, packages/app/src/background/services/injector/__tests__/injector.test.ts, packages/app/src/background/services/lock/__tests__/lockerService.test.ts, packages/app/src/background/services/lock/index.ts, packages/app/src/background/services/zkIdentity/index.ts, packages/app/src/ui/ducks/app.ts, packages/app/src/ui/ducks/requests.ts, packages/app/src/ui/pages/Login/__tests__/Login.test.tsx, packages/app/src/ui/pages/Login/__tests__/useLogin.test.ts, packages/app/src/ui/pages/Login/useLogin.ts, packages/demo/index.tsx
This PR changes checks if there is a connected identity before sending a new request to connect identity page.
* Blocked by #966 
* Fixes #965 
* Fixes #992 
N/A
N/A
=> fix: check connected identity on `connect()`

nx.json, package.json, packages/app/src/background/services/base/Base.ts, packages/app/src/background/services/injector/InjectorHandler.ts, packages/app/src/background/services/injector/__tests__/injector.test.ts, packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts, packages/app/src/background/services/zkIdentity/index.ts, packages/app/src/config/mock/zk.ts, packages/app/src/types/history/index.ts, packages/app/src/ui/components/IdentityList/Item/index.tsx, packages/app/src/ui/components/IdentityList/__tests__/IdentityList.test.tsx, packages/app/src/ui/ducks/__tests__/identities.test.tsx, packages/app/src/ui/pages/ConnectIdentity/__tests__/ConnectedIdentity.test.tsx, packages/app/src/ui/pages/Home/__tests__/useHome.test.ts, packages/app/src/ui/pages/Home/components/ActivityList/Item/ActivityListItem.tsx, packages/app/src/ui/pages/Identity/Identity.tsx, packages/app/src/ui/pages/Identity/__tests__/Idenity.test.tsx, packages/app/src/ui/pages/RevealIdentityCommitment/RevealIdentityCommitment.tsx, packages/types/src/identity/index.ts, packages/types/src/index.ts, packages/zk/src/identity/factory/__tests__/factory.test.ts, packages/zk/src/identity/factory/index.ts, packages/zk/src/identity/protocols/__tests__/zkIdentitySemaphore.test.ts, packages/zk/src/proof/protocols/__tests__/proofs.test.ts, pnpm-lock.yaml
This PR adds support for adding new identities from background script side.
Blocked by #975 
Related to #906 
N/A
N/A
=> feat: import identity

packages/app/src/background/cryptKeeper.ts, packages/app/src/background/services/base/Base.ts, packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts, packages/app/src/background/services/zkIdentity/index.ts
This PR unlocks approval and identity services when user login
Related to #963
N/A
Check login/logout for different cases: onboarding, login (with approval, with connect, with only one or without any).
=> fix: unlock approval and identity services

packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts, packages/app/src/background/services/zkIdentity/index.ts, packages/app/src/config/mock/wallet.ts, packages/app/src/ui/components/DropdownButton/DropdownButton.tsx, packages/app/src/ui/components/DropdownButton/__tests__/DropdownButton.test.tsx, packages/app/src/ui/components/DropdownButton/index.ts, packages/app/src/ui/ducks/__tests__/identities.test.tsx, packages/app/src/ui/hooks/wallet/__tests__/useSignatureOptions.test.ts, packages/app/src/ui/hooks/wallet/index.ts, packages/app/src/ui/hooks/wallet/useSignatureOptions.ts, packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx, packages/app/src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx, packages/app/src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts, packages/app/src/ui/pages/CreateIdentity/useCreateIdentity.ts, packages/app/src/ui/pages/ImportIdentity/ImportIdentity.tsx, packages/app/src/ui/pages/ImportIdentity/__tests__/ImportIdentity.test.tsx, packages/app/src/ui/pages/ImportIdentity/__tests__/useImportIdentity.test.ts, packages/app/src/ui/pages/ImportIdentity/useImportIdentity.ts, packages/app/src/ui/pages/PresentVerifiableCredential/PresentVerifiableCredential.tsx, packages/app/src/ui/services/identity/__tests__/identity.test.ts, packages/app/src/ui/services/identity/index.ts, packages/e2e/pages/cryptKeeper/Identities.ts, packages/e2e/tests/importExternalIdentity.test.ts, packages/types/src/identity/index.ts, packages/zk/src/identity/factory/index.ts, packages/zk/src/proof/protocols/__tests__/utils.test.ts, pnpm-lock.yaml
This PR adds support for importing identities and derive them from user's seed phrase.
Blocked by #1040 
Related to #906
<details>
<summary>Expand</summary>
</details>
1. Try to import identity from demo, connect, create identity screens.
2. Check cryptkeeper sign
3. Check metamask sign with and without connect
=> feat: derive import identities from seed phrase 

packages/app/src/background/services/approval/index.ts, packages/app/src/background/services/base/Base.ts, packages/app/src/background/services/connection/ConnectionService.ts, packages/app/src/background/services/connection/__tests__/ConnectionService.test.ts, packages/app/src/background/services/connection/index.ts, packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts, packages/app/src/background/services/zkIdentity/index.ts, packages/providers/src/services/event/types.ts, packages/types/src/identity/index.ts, packages/types/src/index.ts
This PR adds support for new connection service.
Blocked by #1046
Related to #945 
N/A
Check identities are loaded properly for backup, after delete, add and update.
=> feat: add connection service
